//
// Copyright © 2026 Stream.io Inc. All rights reserved.
//

import Foundation

extension ObjectLifecycle {
    /// A recorded lifecycle transition for a tracked object instance.
    struct Event: Sendable, Equatable {
        /// The transition that occurred.
        let transition: Transition
        /// Type name of the tracked object.
        let typeName: String
        /// Stable per-instance identifier generated by the tracker.
        let instanceId: String
        /// Timestamp of when the transition was recorded.
        let timestamp: Date
        /// Optional metadata attached by the tracked object.
        let metadata: [String: String]
    }
}
