coverage_service: sonarqube_xml
xcodeproj: StreamVideo.xcodeproj
scheme: StreamVideo
configuration: Test
source_directory: Sources/
output_directory: reports
ignore:
  - "**/*_Vendor.swift"
  - "**/Generated/"
  - "**/protobuf/"
  - "**/OpenApi/"
