# Directory and file filters
included:
  - Sources
  - DemoApp
  - DemoAppUIKit
excluded:
  - Tests/SwiftLintFrameworkTests/Resources
  - Sources/StreamVideo/Generated
  - Sources/StreamVideo/OpenApi
  - Sources/StreamVideo/protobuf
  - Sources/StreamVideoSwiftUI/Generated

# Custom Rules
custom_rules:
  discourage_task_init:
    name: "Discouraged Task { usage"
    regex: '\bTask\s*\{'
    message: "Avoid using Task { directly. Prefer adding the Task in a disposable bag to offer some basic lifecycle management."
    severity: error
    excluded:
      - DemoApp
      - DemoAppUIKit
      - Sources/StreamVideoSwiftUI
      - Sources/StreamVideoUIKit

# Enabled/disabled rules
only_rules:
  - unhandled_throwing_task
  # - custom_rules