# Directory and file filters
included:
  - Sources
  - DemoApp
  - DemoAppUIKit
excluded:
  - Tests/SwiftLintFrameworkTests/Resources
  - Sources/StreamVideo/Generated
  - Sources/StreamVideo/OpenApi
  - Sources/StreamVideo/protobuf
  - Sources/StreamVideoSwiftUI/Generated

# Custom Rules
custom_rules:
  discourage_timer_publish:
    name: "Discouraged Timer.publish usage"
    regex: '\bTimer\s*(\.\s*)?publish\b'
    message: "Avoid using Timer.publish. User the TimerStorage instead."
    severity: error

# Enabled/disabled rules
only_rules:
  - unhandled_throwing_task
  - custom_rules