name: 'Xcode Cache'
description: 'Cache Xcode dependencies'
runs:
  using: "composite"
  steps:
    - run: echo "IMAGE=${ImageOS}-${ImageVersion}" >> $GITHUB_ENV
      shell: bash
    - name: Cache SPM
      uses: actions/cache@v4
      id: spm-cache
      with:
        path: spm_cache
        key: ${{ env.IMAGE }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: ${{ env.IMAGE }}-spm-
