name: 'Xcode Cache'
description: 'Cache Xcode dependencies'
runs:
  using: "composite"
  steps:
    - name: Cache Xcode
      uses: irgaly/xcode-cache@v1
      with:
        key: xcode-cache-deriveddata-${{ github.workflow }}-${{ hashFiles('**/Package.resolved') }}-${{ github.ref_name }}
        restore-keys: |
          xcode-cache-deriveddata-${{ github.workflow }}-${{ hashFiles('**/Package.resolved') }}
          xcode-cache-deriveddata-${{ github.workflow }}-${{ github.ref_name }}-
          xcode-cache-deriveddata-${{ github.workflow }}-
        deriveddata-directory: ${{ github.workspace }}/derived_data
        swiftpm-cache-key: xcode-cache-spm-${{ hashFiles('**/Package.resolved') }}
        swiftpm-cache-restore-keys: xcode-cache-spm-
        sourcepackages-directory: ${{ github.workspace }}/spm_cache
        verbose: true
