default_platform :ios
skip_docs

require 'json'
require 'net/http'
import 'Sonarfile'
import 'Allurefile'

xcode_version = ENV['XCODE_VERSION'] || '14.2'
xcode_project = 'StreamVideo.xcodeproj'
sdk_names = ['StreamVideo', 'StreamVideoSwiftUI']
github_repo = ENV['GITHUB_REPOSITORY'] || 'GetStream/stream-video-swift'
sinatra_port = 4567
video_buddy_port = 5678

before_all do |lane|
  if is_ci
    setup_ci
    ENV['FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT'] = '180'
    xcodes(version: xcode_version, select_for_current_build_only: true) unless [:publish_release, :allure_launch].include?(lane)
  end
end

after_all do |lane|
  if lane == :test_e2e
    stop_sinatra
    stop_video_buddy
  end
end

desc "Release a new version"
lane :release do |options|
  release_ios_sdk(
    version: options[:version],
    bump_type: options[:type],
    sdk_names: sdk_names,
    github_repo: github_repo,
    pod_sync: options[:pod_sync], # `false` by default
    skip_pod_list: true # Needs to be set to `false` after first release
  )
end

lane :match_me do |options|
  custom_match(
    api_key: appstore_api_key,
    app_identifier: [
      'io.getstream.iOS.VideoDemoApp',
      'io.getstream.iOS.DemoAppUIKit',
      'io.getstream.iOS.VideoDemoApp.CallIntent'
    ],
    readonly: options[:readonly],
    register_device: options[:register_device]
  )
end

lane :swiftui_testflight_build do
  upload_beta(app_target: 'DemoApp', app_identifier: 'io.getstream.iOS.VideoDemoApp')
end

lane :uikit_testflight_build do
  upload_beta(app_target: 'DemoAppUIKit', app_identifier: 'io.getstream.iOS.DemoAppUIKit')
end

private_lane :upload_beta do |options|
  match_me
  testflight_build(
    api_key: appstore_api_key,
    xcode_project: xcode_project,
    sdk_target: 'StreamVideo',
    app_target: options[:app_target],
    app_identifier: options[:app_identifier]
  )
end

private_lane :appstore_api_key do
  @appstore_api_key ||= app_store_connect_api_key(
    key_id: 'MT3PRT8TB7',
    issuer_id: '69a6de96-0738-47e3-e053-5b8c7c11a4d1',
    key_content: ENV.fetch('APPSTORE_API_KEY', nil),
    in_house: false
  )
end

desc 'Runs LLC tests in Debug config'
lane :test do |options|
  next unless is_check_required(sources: sources_matrix[:unit])

  update_testplan_on_ci(path: 'StreamVideoTests/StreamVideo.xctestplan')

  scan(
    project: xcode_project,
    scheme: 'StreamVideo',
    testplan: 'StreamVideo',
    clean: true,
    devices: options[:device]
  )
end

desc 'Runs SwiftUI tests in Debug config'
lane :test_swiftui do |options|
  next unless is_check_required(sources: sources_matrix[:swiftui])

  remove_snapshots if options[:record]

  update_testplan_on_ci(path: 'StreamVideoSwiftUITests/StreamVideoSwiftUI.xctestplan')

  scan(
    project: xcode_project,
    scheme: 'StreamVideoSwiftUI',
    testplan: 'StreamVideoSwiftUI',
    clean: true,
    result_bundle: true,
    devices: options[:device],
    build_for_testing: options[:build_for_testing]
  )
end

desc 'Runs UIKit tests in Debug config'
lane :test_uikit do |options|
  next unless is_check_required(sources: sources_matrix[:uikit])

  remove_snapshots if options[:record]

  update_testplan_on_ci(path: 'StreamVideoUIKitTests/StreamVideoUIKit.xctestplan')

  scan(
    project: xcode_project,
    scheme: 'StreamVideoUIKit',
    testplan: 'StreamVideoUIKit',
    clean: true,
    result_bundle: true,
    devices: options[:device],
    build_for_testing: options[:build_for_testing]
  )
end

desc 'Starts Sinatra web server'
lane :start_sinatra do
  sh('nohup bundle exec ruby sinatra.rb > sinatra-log.txt 2>&1 &')
end

desc 'Stops Sinatra web server'
lane :stop_sinatra do
  sh("lsof -t -i:#{sinatra_port} | xargs kill -9")
end

desc 'Starts Stream Video Buddy'
lane :start_video_buddy do
  sh("stream-video-buddy auth --record-session")
  sh("nohup stream-video-buddy server --port #{video_buddy_port} > video-buddy-log.txt 2>&1 &")
end

desc 'Stops Stream Video Buddy'
lane :stop_video_buddy do
  sh("lsof -t -i:#{video_buddy_port} | xargs kill -9")
end

desc 'Runs e2e ui tests in Debug config'
lane :test_e2e do |options|
  next unless is_check_required(sources: sources_matrix[:e2e])

  update_testplan_on_ci(path: 'SwiftUIDemoAppUITests/SwiftUIDemoApp.xctestplan')

  start_sinatra
  start_video_buddy

  device = options[:ios] && options[:ios] != 'latest' ? "#{options[:device]} (#{options[:ios]})" : options[:device]
  prepare_simulator(device: device) if is_ci && (options[:ios].nil? || ['latest', '15.4'].include?(options[:ios]))

  scan_options = {
    project: xcode_project,
    scheme: 'DemoApp',
    testplan: 'SwiftUIDemoApp',
    result_bundle: true,
    devices: device,
    number_of_retries: 2
  }

  build_for_testing = is_ci && options[:cron].nil?
  scan(scan_options.merge(clean: true, build_for_testing: build_for_testing))

  if build_for_testing
    parallelize_tests_on_ci(
      scan: scan_options,
      derived_data: lane_context[SharedValues::SCAN_DERIVED_DATA_PATH],
      batch: options[:batch]
    )
  end
end

private_lane :parallelize_tests_on_ci do |options|
  xctestrun = Dir.glob("#{options[:derived_data]}/Build/Products/*.xctestrun").first
  tests = retrieve_xctest_names(xctestrun: xctestrun).values.flatten
  slice_size = (tests.size / ENV['MATRIX_SIZE'].to_f).ceil
  only_testing = []
  tests.each_slice(slice_size) { |test| only_testing << test }
  only_testing_batch = only_testing[options[:batch].to_i]

  UI.success("Tests in total: #{only_testing.flatten.size}. Running #{only_testing_batch.size} of them ⌛️")
  scan(
    options[:scan].merge(
      test_without_building: true,
      derived_data_path: options[:derived_data],
      only_testing: only_testing_batch
    )
  )
end

private_lane :update_testplan_on_ci do |options|
  update_testplan(path: options[:path], env_vars: { key: 'CI', value: 'TRUE' }) if is_ci || options[:force]
end

desc 'Builds SwiftUI Demo app'
lane :build_swiftui_demo do
  build_example_app(scheme: 'DemoApp')
end

desc 'Builds UIKit Demo app'
lane :build_uikit_demo do
  build_example_app(scheme: 'DemoAppUIKit')
end

private_lane :build_example_app do |options|
  app_sources =
    case options[:scheme]
    when 'DemoApp'
      :swiftui_sample_apps
    when 'DemoAppUIKit'
      :uikit_sample_apps
    end
  next unless is_check_required(sources: sources_matrix[app_sources])

  scan(
    project: xcode_project,
    scheme: options[:scheme],
    clean: true,
    build_for_testing: true
  )
end

lane :emerge_swiftui do
  next unless is_check_required(sources: sources_matrix[:emerge_swiftui])

  emerge_upload(scheme: 'DemoApp')
end

lane :emerge_uikit do
  next unless is_check_required(sources: sources_matrix[:emerge_uikit])

  emerge_upload(scheme: 'DemoApp')
end

desc 'Build and upload DemoApp to Emerge'
private_lane :emerge_upload do |options|
  gym(
    export_method: 'ad-hoc',
    project: xcode_project,
    scheme: options[:scheme],
    skip_package_ipa: true,
    skip_archive: false,
    clean: true
  )

  emerge(
    build_type: 'release',
    repo_name: github_repo,
    pr_number: ENV['GITHUB_PR_NUM'] || nil, # If `nil` then local run or merge to develop/main
    sha: last_git_commit[:commit_hash]
  )
end

desc 'Run fastlane linting'
lane :rubocop do
  next unless is_check_required(sources: sources_matrix[:ruby])

  sh('bundle exec rubocop')
end

desc 'Run source code linting'
lane :run_linter do
  Dir.chdir('..') do
    sh('mint run swiftformat --lint --config .swiftformat Sources --exclude **/Generated, **/generated, **/protobuf')
  end
end

desc 'Remove SwiftUI snapshots'
private_lane :remove_snapshots do |options|
  Dir.glob("../#{options[:scheme]}Tests/**/__Snapshots__/**/*.png").select { |file| File.delete(file) }
end

lane :sources_matrix do
  {
    e2e: ['Sources', 'DemoApp', xcode_project],
    unit: ['Sources', 'StreamVideoTests', xcode_project],
    swiftui: ['Sources', 'StreamVideoSwiftUITests', xcode_project],
    emerge_swiftui: ['Sources/StreamVideoSwiftUI', 'Sources/StreamVideo', xcode_project],
    emerge_uikit: ['Sources/StreamVideoUIKit'],
    uikit: ['Sources', 'StreamVideoUIKitTests', xcode_project],
    swiftui_sample_apps: ['Sources', 'DemoApp', xcode_project],
    uikit_sample_apps: ['Sources', 'DemoAppUIKit', xcode_project],
    ruby: ['fastlane']
  }
end

private_lane :current_branch do
  ENV['BRANCH_NAME'] || git_branch
end
