#!/usr/bin/env ruby

desc 'Get code coverage report and run complexity analysis for Sonar'
lane :sonar_upload do
  next unless is_check_required(sources: sources_matrix[:llc], force_check: @force_check)

  version_number = get_version_number(
    xcodeproj: 'StreamVideo.xcodeproj',
    target: 'StreamVideo'
  )[/\d+\.\d+\.\d/]

  Dir.chdir('..') do
    sh("./fastlane/sonar/bin/sonar-scanner " \
       "-Dsonar.projectVersion=#{version_number} " \
       "-Dproject.settings=sonar-project.properties " \
       "-Dsonar.coverageReportPaths='reports/sonarqube-generic-coverage.xml'")
  end
end
