//
// Copyright © 2022 Stream.io Inc. All rights reserved.
//

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
private struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
    struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
    typealias Version = _2
}

enum Stream_Video_Coordinator_GeofenceV1_GeofenceType: SwiftProtobuf.Enum {
    typealias RawValue = Int
    case unspecified // = 0
    case inclusion // = 1
    case exclusion // = 2
    case UNRECOGNIZED(Int)

    init() {
        self = .unspecified
    }

    init?(rawValue: Int) {
        switch rawValue {
        case 0: self = .unspecified
        case 1: self = .inclusion
        case 2: self = .exclusion
        default: self = .UNRECOGNIZED(rawValue)
        }
    }

    var rawValue: Int {
        switch self {
        case .unspecified: return 0
        case .inclusion: return 1
        case .exclusion: return 2
        case let .UNRECOGNIZED(i): return i
        }
    }
}

#if swift(>=4.2)

extension Stream_Video_Coordinator_GeofenceV1_GeofenceType: CaseIterable {
    // The compiler won't synthesize support with the UNRECOGNIZED case.
    static var allCases: [Stream_Video_Coordinator_GeofenceV1_GeofenceType] = [
        .unspecified,
        .inclusion,
        .exclusion
    ]
}

#endif // swift(>=4.2)

struct Stream_Video_Coordinator_GeofenceV1_Geofence {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// Unique name of the geofence.
    var name: String = String()

    /// Type of the geofence, to included or to exclude the countries.
    var type: Stream_Video_Coordinator_GeofenceV1_GeofenceType = .unspecified

    /// Alpha-2 country codes to be included or excluded.
    var countryCodes: [String] = []

    /// Description of the geofence.
    var description_p: String = String()

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}
}

#if swift(>=5.5) && canImport(_Concurrency)
extension Stream_Video_Coordinator_GeofenceV1_GeofenceType: @unchecked Sendable {}
extension Stream_Video_Coordinator_GeofenceV1_Geofence: @unchecked Sendable {}
#endif // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

private let _protobuf_package = "stream.video.coordinator.geofence_v1"

extension Stream_Video_Coordinator_GeofenceV1_GeofenceType: SwiftProtobuf._ProtoNameProviding {
    static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        0: .same(proto: "GEOFENCE_TYPE_UNSPECIFIED"),
        1: .same(proto: "GEOFENCE_TYPE_INCLUSION"),
        2: .same(proto: "GEOFENCE_TYPE_EXCLUSION")
    ]
}

extension Stream_Video_Coordinator_GeofenceV1_Geofence: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = _protobuf_package + ".Geofence"
    static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "name"),
        2: .same(proto: "type"),
        3: .standard(proto: "country_codes"),
        4: .same(proto: "description")
    ]

    mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
            case 2: try { try decoder.decodeSingularEnumField(value: &self.type) }()
            case 3: try { try decoder.decodeRepeatedStringField(value: &self.countryCodes) }()
            case 4: try { try decoder.decodeSingularStringField(value: &self.description_p) }()
            default: break
            }
        }
    }

    func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        if !name.isEmpty {
            try visitor.visitSingularStringField(value: name, fieldNumber: 1)
        }
        if type != .unspecified {
            try visitor.visitSingularEnumField(value: type, fieldNumber: 2)
        }
        if !countryCodes.isEmpty {
            try visitor.visitRepeatedStringField(value: countryCodes, fieldNumber: 3)
        }
        if !description_p.isEmpty {
            try visitor.visitSingularStringField(value: description_p, fieldNumber: 4)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (lhs: Stream_Video_Coordinator_GeofenceV1_Geofence, rhs: Stream_Video_Coordinator_GeofenceV1_Geofence) -> Bool {
        if lhs.name != rhs.name { return false }
        if lhs.type != rhs.type { return false }
        if lhs.countryCodes != rhs.countryCodes { return false }
        if lhs.description_p != rhs.description_p { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}
