name: Publish Docusaurus to staging

on:
  push:
    branches:
      - main
    paths:
      - 'docusaurus/**'

jobs:
  push_docusaurus:
    name: Publish docusaurus docs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3.1.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: push
        uses: GetStream/push-stream-chat-docusaurus-action@main
        with:
          target-branch: 'staging'
          destination-repository-name: 'stream-video-docusaurus'
        env:
          DOCUSAURUS_GH_TOKEN: ${{ secrets.DOCUSAURUS_GH_TOKEN }}
