name: Record Snapshots

on:
  workflow_dispatch:
    inputs:
      record_snapshots_swiftui:
        description: 'SwiftUI snapshots'
        type: boolean
        required: false
        default: true
      remove_and_record_snapshots_swiftui:
        description: 'Remove existing SwiftUI snapshots before recording the new ones?'
        type: boolean
        required: false
        default: false
      record_snapshots_uikit:
        description: 'UIKit snapshots'
        type: boolean
        required: false
        default: false
      remove_and_record_snapshots_uikit:
        description: 'Remove existing UIKit snapshots before recording the new ones?'
        type: boolean
        required: false
        default: false

jobs:
  record:
    name: Record
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1
    - run: |
        gh workflow run smoke-checks.yml --ref "${GITHUB_REF#refs/heads/}" \
          -f record_snapshots_swiftui=${{ github.event.inputs.record_snapshots_swiftui }} \
          -f remove_and_record_snapshots_swiftui=${{ github.event.inputs.remove_and_record_snapshots_swiftui }} \
          -f record_snapshots_uikit=${{ github.event.inputs.record_snapshots_uikit }} \
          -f remove_and_record_snapshots_uikit=${{ github.event.inputs.remove_and_record_snapshots_uikit }}
      timeout-minutes: 5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
